version: "3.9"

services:
  db:
    image: postgres:15-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    container_name: blog-go-db
    environment:
      - POSTGRES_DB=blog_go_db
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: gin.Dockerfile
    container_name: blog-go-api
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://devuser:admin@db:5432/blog_go_db?sslmode=disable
      - SERVER_TYPE=gin
    depends_on:
      - db
    entrypoint: ["/app/wait-for.sh", "db:5432", "--", "/app/start.sh"]
    command: ["/app/main"]

  # gRPC
#  gapi:
#    build:
#      context: .
#      dockerfile: grpc.Dockerfile
#    container_name: blog-go-gapi
#    ports:
#      - "9090:9090"
#    environment:
#      - DB_SOURCE=postgresql://devuser:admin@db:5432/blog_go_db?sslmode=disable
#      - SERVER_TYPE=gRPC
#    depends_on:
#      - db
#    entrypoint: [ "/app/wait-for.sh", "db:5432", "--", "/app/start.sh" ]
#    command: [ "/app/main" ]

volumes:
  dev-db-data: