// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: post_tags.sql

package db

import (
	"context"
)

const addTagToPost = `-- name: AddTagToPost :exec
INSERT INTO post_tags
    (post_id, tag_id)
VALUES ($1, $2)
`

type AddTagToPostParams struct {
	PostID int64 `json:"post_id"`
	TagID  int32 `json:"tag_id"`
}

func (q *Queries) AddTagToPost(ctx context.Context, arg AddTagToPostParams) error {
	_, err := q.db.ExecContext(ctx, addTagToPost, arg.PostID, arg.TagID)
	return err
}

const removeTagFromPost = `-- name: RemoveTagFromPost :exec
DELETE
FROM post_tags
WHERE post_id = $1
  AND tag_id = $2
`

type RemoveTagFromPostParams struct {
	PostID int64 `json:"post_id"`
	TagID  int32 `json:"tag_id"`
}

func (q *Queries) RemoveTagFromPost(ctx context.Context, arg RemoveTagFromPostParams) error {
	_, err := q.db.ExecContext(ctx, removeTagFromPost, arg.PostID, arg.TagID)
	return err
}
