// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"
)

type Querier interface {
	AddMultipleTagsToPost(ctx context.Context, arg AddMultipleTagsToPostParams) error
	AddTagToPost(ctx context.Context, arg AddTagToPostParams) error
	CreateCategory(ctx context.Context, name string) (Category, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateTag(ctx context.Context, name string) (Tag, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCategory(ctx context.Context, name string) error
	DeleteComment(ctx context.Context, id int64) error
	DeletePost(ctx context.Context, id int64) error
	DeleteTag(ctx context.Context, name string) error
	DeleteTagsFromPost(ctx context.Context, arg DeleteTagsFromPostParams) error
	DeleteUser(ctx context.Context, email string) error
	GetComment(ctx context.Context, id int64) (GetCommentRow, error)
	GetMinimalPostData(ctx context.Context, id int64) (GetMinimalPostDataRow, error)
	GetOrCreateCategory(ctx context.Context, name string) (int64, error)
	GetOrCreateTags(ctx context.Context, tagNames []string) ([]int32, error)
	GetPostByID(ctx context.Context, id int64) (GetPostByIDRow, error)
	GetPostByTitle(ctx context.Context, title string) (GetPostByTitleRow, error)
	GetTagsOfPost(ctx context.Context, postID int64) ([]Tag, error)
	GetUser(ctx context.Context, email string) (User, error)
	ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error)
	ListCommentsForPost(ctx context.Context, arg ListCommentsForPostParams) ([]Comment, error)
	ListPosts(ctx context.Context, arg ListPostsParams) ([]ListPostsRow, error)
	ListPostsByAuthor(ctx context.Context, arg ListPostsByAuthorParams) ([]ListPostsByAuthorRow, error)
	ListPostsByCategory(ctx context.Context, arg ListPostsByCategoryParams) ([]ListPostsByCategoryRow, error)
	ListPostsByTags(ctx context.Context, arg ListPostsByTagsParams) ([]ListPostsByTagsRow, error)
	ListTagIDsByNames(ctx context.Context, tagNames []string) ([]int32, error)
	ListTags(ctx context.Context, arg ListTagsParams) ([]Tag, error)
	ListUsersContainingString(ctx context.Context, str string) ([]User, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
	UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error)
}

var _ Querier = (*Queries)(nil)
